// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfduRBUOkTLIG1ri9TR_MUKIS3JYlHPg4',
    appId: '1:574647577224:web:22cc8be03495375eb48d3d',
    messagingSenderId: '574647577224',
    projectId: 'hidron-98166',
    authDomain: 'hidron-98166.firebaseapp.com',
    storageBucket: 'hidron-98166.firebasestorage.app',
    measurementId: 'G-G3EX8BX2QV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNV_TPsS2tDGQzoTx-_E8m0cjw-n6hYmw',
    appId: '1:574647577224:android:3f1456693889321ab48d3d',
    messagingSenderId: '574647577224',
    projectId: 'hidron-98166',
    storageBucket: 'hidron-98166.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd3o9kwgujlE0_yL2JOsnb8EShcmYvbzo',
    appId: '1:574647577224:ios:d1adc07ef2dc3059b48d3d',
    messagingSenderId: '574647577224',
    projectId: 'hidron-98166',
    storageBucket: 'hidron-98166.firebasestorage.app',
    iosBundleId: 'com.example.offlineDealsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd3o9kwgujlE0_yL2JOsnb8EShcmYvbzo',
    appId: '1:574647577224:ios:d1adc07ef2dc3059b48d3d',
    messagingSenderId: '574647577224',
    projectId: 'hidron-98166',
    storageBucket: 'hidron-98166.firebasestorage.app',
    iosBundleId: 'com.example.offlineDealsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfduRBUOkTLIG1ri9TR_MUKIS3JYlHPg4',
    appId: '1:574647577224:web:c2824a02fcc9be09b48d3d',
    messagingSenderId: '574647577224',
    projectId: 'hidron-98166',
    authDomain: 'hidron-98166.firebaseapp.com',
    storageBucket: 'hidron-98166.firebasestorage.app',
    measurementId: 'G-7S5HDR3N1R',
  );

}